config/routes.rb
Rails.application.routes.draw do
  get 'stats', to: 'stats#index'
  get 'versions', to: 'versions#index'

  resources :users
  resources :events do
    get :cancel, on: :member
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: [:new, :create]
    patch :preview, on: :member
    get :validate, :refuse, on: :member
    put :accept, on: :member
  end
  resources :digests, only: [:index, :show]
  resources :regions, only: [:index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: [:index, :show]
  resources :maps, only: [:index, :show]
  resources :orgas do
    get :cancel, :validate, :refuse, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users,
             path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/controllers/moderations_controller.rb
# Event management life cycle
class ModerationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_moderation, :set_mailer_host, only:
    [:show, :edit, :preview, :update, :validate, :accept, :refuse, :destroy]
  before_action :generate_destroy_reason, only: :destroy
  rescue_from ActiveRecord::StaleObjectError, with: :locked

  def index
    @events = Event.unmoderated
    @orgas = Orga.unmoderated
  end

  def preview
    @moderation.attributes = moderation_params
    @moderation.valid?
    render action: :edit
  end

  # PATCH/PUT /moderations/1
  # PATCH/PUT /moderations/1.json
  def update
    respond_to do |format|
      if @moderation.update_attributes moderation_params
        format.html { redirect_to :moderations, notice: t('.ok') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        # 422 means :unprocessable_entity
        format.json { render json: @moderation.errors, status: 422 }
      end
    end
  end

  # PATCH/PUT /accept/1
  # PATCH/PUT /accept/1.json
  def accept
    @moderation.update moderated: true
    respond_to do |format|
      format.html { redirect_to :moderations, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @moderation.destroy!
    respond_to do |format|
      format.html { redirect_to :moderations, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_moderation
    @event = Event.find params[:id]
    @moderation = @event
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def moderation_params
    params.require(:event)
          .permit :lock_version, :title, :start_time, :end_time, :repeat, :rule,
                  :description, :place_name, :address, :city, :region_id,
                  :locality, :url, :contact, :submitter, :tag_list
  end

  # Useful to manage absolute url in mails
  def set_mailer_host
    ActionMailer::Base.default_url_options[:host] = request.host_with_port
  end

  def locked
    redirect_to edit_moderation_url(@moderation), alert: t('staleObjectError')
  end

  def generate_destroy_reason
    if params[:reason] == 'r_4'
      @moderation.reason = params[:event][:reason]
    else
      @moderation.reason = t "moderations.refuse.reason_#{params[:reason]}_long"
    end
  end
end

app/helpers/moderations_helper.rb
# Helper for the moderation views
module ModerationsHelper
end

app/views/moderations/edit.html.haml
%h2
  %em.fa.fa-pencil
  =t '.title'

- if @moderation.moderated?
  %h3.warning
    %em.fa.fa-warning
    =t '.warning'

%fieldset
  %legend
    %em.fa.fa-eye
    =t '.preview'
  = render file: '/events/show'

%fieldset
  %legend
    %em.fa.fa-pencil
    =t '.edit'
  = render '/events/form'

app/views/moderations/index.html.haml
%h2
  %em.fa.fa-gavel
  = title t '.title'

:markdown
  #### #{t '.rules'}

- if @orgas.present?
  %table.list
    %thead
      %tr
        %th= Orga.human_attribute_name :name
        %th= Orga.human_attribute_name :city
        %th= Orga.human_attribute_name :region
        %th= Orga.human_attribute_name :submission_time
        %th= t '.actions'

    %tbody
      - @orgas.each do |orga|
        %tr
          %td= orga.name
          %td= orga.city
          %td= orga.region
          %td= time_ago_in_words orga.submission_time
          %th.actions
            = link_to edit_orga_path orga do
              %em.fa.fa-pencil
              = t 'edit'
            \-
            = link_to validate_orga_path orga do
              %em.fa.fa-thumbs-up
              = t 'validate'
            \-
            = link_to cancel_orga_path orga do
              %em.fa.fa-thumbs-down
              = t 'refuse'

- if @events.present?
  %table.list
    %thead
      %tr
        %th= Event.human_attribute_name :title
        %th
          = Event.human_attribute_name :start_time
          \-
          = Event.human_attribute_name :end_time
        %th= Event.human_attribute_name :city
        %th= Event.human_attribute_name :region
        %th= Event.human_attribute_name :submission_time
        %th= t '.actions'

    %tbody
      - @events.each do |event|
        %tr
          %td= event.title
          %td= display_date event
          %td= event.city
          %td= event.region.name
          %td= time_ago_in_words event.submission_time
          %th.actions
            = link_to edit_moderation_path event do
              %em.fa.fa-pencil
              = t 'edit'
            \-
            = link_to validate_moderation_path event do
              %em.fa.fa-thumbs-up
              = t 'validate'
            \-
            = link_to refuse_moderation_path event do
              %em.fa.fa-thumbs-down
              = t 'refuse'
            \-
            = link_to new_moderation_note_path event, envoiParMail: :oui do
              %em.fa.fa-bullhorn
              = t '.askInfos'
            \-
            = link_to new_moderation_note_path event do
              %em.fa.fa-paperclip
              = t '.createNote'

        - event.notes.each do |note|
          %tr
            %td.empty/
            %td.note(colspan="5")
              = raw note.contents
              %em.author
                = t '.posted_by',
                  author: "#{note.author.firstname} #{note.author.lastname}",
                  date: l(note.date, format: :at) rescue nil

.logout
  = link_to destroy_user_session_path, method: :delete do
    %em.fa.fa-sign-out
    = t 'logout'

app/views/moderations/refuse.html.haml
%h2
  %em.fa.fa-exclamation-triangle
  = t '.title'

= form_for @moderation, url: { action: :destroy },
  html: { method: :delete } do |f|
  .field.closer{ title: t('.reason_r_1_long') }
    = radio_button_tag :reason, :r_1, params[:event] == 'reason_r_1'
    = label_tag :reason_r_1, t('.reason_r_1')

  .field.closer{ title: t('.reason_r_2_long') }
    = radio_button_tag :reason, :r_2, params[:event] == 'reason_r_2'
    = label_tag :reason_r_2, t('.reason_r_2')

  .field.closer{ title: t('.reason_r_3_long') }
    = radio_button_tag :reason, :r_3, params[:event] == 'reason_r_3'
    = label_tag :reason_r_3, t('.reason_r_3')

  .field.opener
    = radio_button_tag :reason, :r_4,
      params[:event] == 'reason_r_4' || !params[:event]
    = label_tag :reason_r_4, t('.reason_r_4')

  .field.reason
    = f.label :reason
    = f.text_area :reason, cols: 40, rows: 5

  = link_to moderations_path do
    %em.fa.fa-arrow-left
    = t '.ko'

  = button_tag do
    %em.fa.fa-thumbs-down
    = t '.ok'

%fieldset
  %legend
    %em.fa.fa-calendar
    = Event.model_name.human
  = render file: '/events/show'

app/views/moderations/validate.html.haml
%h2
  %em.fa.fa-exclamation-triangle
  = t '.title'

- if @event.locality?
  %h2.warning= t '.warning'

= form_for @moderation, url: { action: :accept }, html: { method: :put } do |f|
  = link_to moderations_path do
    %em.fa.fa-arrow-left
    = t '.ko'

  = f.button do
    %em.fa.fa-thumbs-up
    = t '.ok'

- if ENV['TWITTER_CONSUMER_KEY'] || Rails.env.development?
  %fieldset
    %legend
      %em.fa.fa-twitter
      Tweet

    %h3= t '.tweet_helper'

    = @event.to_tweet

- if @event.repeat > 0
  %fieldset
    %legend
      %em.fa.fa-repeat
      = Event.human_attribute_name :repeat

    %h3= t '.repeat_helper', count: @event.repeat

    %p.rule
      = Event.human_attribute_name :rule
      = t @event.rule, scope: 'activerecord.attributes.event.rule_values'

%fieldset
  %legend
    %em.fa.fa-calendar
    = Event.model_name.human
  = render file: '/events/show'