config/routes.rb
Rails.application.routes.draw do
  get 'stats', to: 'stats#index'
  get 'versions', to: 'versions#index'

  resources :users
  resources :events do
    get :cancel, on: :member
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: [:new, :create]
    patch :preview, on: :member
    get :validate, :refuse, on: :member
    put :accept, on: :member
  end
  resources :digests, only: [:index, :show]
  resources :regions, only: [:index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: [:index, :show]
  resources :maps, only: [:index, :show]
  resources :orgas do
    get :cancel, :validate, :refuse, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users,
             path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/models/orga.rb
# Organisations related to this agenda
class Orga < ActiveRecord::Base
  acts_as_taggable
  strip_attributes
  has_paper_trail ignore: [:last_updated, :secret, :submitter, :decision_time,
                           :lock_version, :latitude, :longitude]

  belongs_to :region
  belongs_to :kind

  validates :kind, presence: true
  validates :name, presence: true
  validates :region, presence: true
  validates :url, format: %r{\Ahttps?:\/\/.*\..*\z}
  validates :diaspora, allow_blank: true, format: %r{\Ahttps?:\/\/.*\..*\z}
  validates :feed, allow_blank: true, format: %r{\Ahttps?:\/\/.*\..*\z}
  validates :contact, allow_blank: true, email: true
  validates :submitter, allow_blank: true, email: true

  geocoded_by :full_address
  # after_validation :geocode, if: -> (obj) { obj.address_changed? }
  after_validation :geocode

  scope :active, -> { where active: true }
  scope :moderated, -> { where moderated: true }
  scope :unmoderated, -> { where moderated: false }

  # Only present to simplify maps_controller, to have the same scopes as events
  scope :locality, -> {}
  scope :daylimit, -> {}
  scope :future, -> {}
  scope :period, ->(_year, _week) {}

  scope :region, ->(region) { where region: region unless region == 'all' }
  scope :tag, ->(tag) { tagged_with tag }
  scope :geo, -> { where 'latitude is not null and longitude is not null' }

  before_validation do
    # Populate submitter using contact info if absent
    self.submitter ||= contact
    self.secret ||= SecureRandom.urlsafe_base64(32)[0...32]
    self.submission_time ||= Time.zone.now
  end

  after_create do
    send_secret
    # Send email to moderators when an new orga is received
    ModerationorgaMailer.create(self).deliver_now!
  end

  after_update do
    send_secret if secret_changed? || submitter_changed?

    if moderated_changed?
      OrgaMailer.accept(self).deliver_now!
      # Send email to moderators when an orga is accepted
      ModerationorgaMailer.accept(self).deliver_now!
    else
      OrgaMailer.update(self).deliver_now!
      # Send email to moderators when an orga is updated
      ModerationorgaMailer.update(self).deliver_now!
    end
  end

  before_destroy do
    OrgaMailer.destroy(self).deliver_now! unless submitter.blank?
    # Send email to moderators when an orga is deleted
    ModerationorgaMailer.destroy(self).deliver_now! unless submitter.blank?
  end

  def send_secret
    OrgaMailer.create(self).deliver_now!
  end

  def name_as_tag
    name.gsub(/\AL'/, '').gsub(/[\s\*']/, '-').delete ':'
  end

  def as_json(_options = {})
    { type: 'Feature', properties: {
      id: id, icon: kind.icon, name: name,
      place_name: place_name, address: address, city: city,
      tags: tags,
      popupContent: "<a href=\"/orgas/#{id}\">#{self}</a>"
    }, geometry: { type: 'Point', coordinates: [longitude, latitude] } }
  end

  def full_address
    # Region seems to disturb openstreetmap :(
    # [address, city, region.try(:name)].compact.join ', '
    [address, city].compact.join ', '
  end

  def to_s
    "[#{kind.name}] #{name}"
  end
end

app/controllers/orgas_controller.rb
# Groups life cycle
class OrgasController < ApplicationController
  has_scope :region
  has_scope :near, type: :hash, using: [:location, :distance]

  before_action :set_orga, except: [:index, :new, :create]
  before_action :set_mailer_host
  before_action :authenticate_user!, except: [:index, :new, :create, :show],
                                     unless: :check_secret

  def index
    @search = apply_scopes(Orga).moderated.includes(:kind,
                                                    :region).search params[:q]
    @search.sorts = 'updated_at desc' if @search.sorts.empty?
    @orgas = @search.result.page params[:page]
  end

  # GET /orgas/new
  def new
    @orga = Orga.new
  end

  # POST /orgas
  # POST /orgas.json
  def create
    @orga = Orga.new orga_params
    respond_to do |format|
      if @orga.save
        format.html { redirect_to :root, notice: t('.ok') }
        # 201 means :created
        format.json { render action: 'show', status: 201, location: @orga }
      else
        format.html { render action: 'new' }
        # 422 means :unprocessable_entity
        format.json { render json: @orga.errors, status: 422 }
      end
    end
  end

  def show
    @search = Orga.search params[:q]

    @events_future = Event.moderated.future.tag @orga.name_as_tag
    @events_past = Event.moderated.past.tag @orga.name_as_tag
  end

  # PATCH/PUT /orgas/1
  # PATCH/PUT /orgas/1.json
  def update
    respond_to do |format|
      if @orga.update orga_params
        format.html { redirect_to @orga, notice: t('.ok') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        # 422 means :unprocessable_entity
        format.json { render json: @orga.errors, status: 422 }
      end
    end
  end

  # PATCH/PUT /accept/1
  # PATCH/PUT /accept/1.json
  def accept
    @orga.update moderated: true
    respond_to do |format|
      format.html { redirect_to :moderations, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  # DELETE /orgas/1
  # DELETE /orgas/1.json
  def destroy
    @orga.destroy
    respond_to do |format|
      format.html { redirect_to :moderations, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_orga
    @orga = Orga.find params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through
  def orga_params
    params.require(:orga)
          .permit :lock_version, :kind_id, :name, :description, :place_name,
                  :address, :city, :department, :region_id, :url, :diaspora,
                  :feed, :contact, :submitter, :tag_list, :active
  end

  # Check that you can only edit an existing event if you know its secret
  def check_secret
    !%w(validate refuse).include?(action_name) &&
      (!@orga.secret || @orga.secret == params[:secret])
  end
end

app/helpers/orgas_helper.rb
# Helper for the orga views
module OrgasHelper
  def set_orga_meta
    set_meta_tags \
      description: strip_tags(@orga.description),
      DC: { title: @orga.name },
      geo: {
        placename: @orga.city,
        region: @orga.region,
        position: "#{@orga.latitude};#{@orga.longitude}",
        ICBM: "#{@orga.latitude}, #{@orga.longitude}"
      }
  end
end

app/views/orgas/_form.html.haml
= form_for @orga do |f|
  - if @orga.persisted?
    = hidden_field_tag :secret, params[:secret]

  - if @orga.errors.any?
    #flash_messages
      - @orga.errors.full_messages.each do |msg|
        %p.flash.alert= msg

  .field.kind
    = f.label :kind
    %span.radios
      - Kind.all.each do |kind|
        = f.radio_button :kind_id, kind.id
        = f.label "kind_id_#{kind.id}" do
          %em.fa{ class: "fa-#{kind.icon}" }
          = Kind.human_attribute_name "name_#{kind.name}"
  .field.name
    = f.label :name
    = f.text_field :name, required: true
  .field.description
    = f.label :description
    = f.text_area :description, rows: 25, class: :description
  .field.place_name
    = f.label :place_name
    = f.text_field :place_name
  .field.address
    .helper
      :markdown
        #{t '.address_helper'}
    = f.label :address
    = f.text_field :address
  .field.city
    = f.label :city
    = f.text_field :city, list: :cities
    %datalist#cities
      - Event.group(:city).order('count(city) desc').pluck(:city).each do |city|
        %option= city
  .field.department
    = f.label :department
    = f.text_field :department
  .field.region
    = f.label :region
    = f.collection_select :region_id, Region.all, :id, :name

  .field.url
    .helper
      :markdown
        #{t '.url_helper'}
    = f.label :url
    = f.url_field :url, placeholder: 'Ex: http://april.org'
  .field.diaspora
    = f.label :diaspora
    = f.url_field :diaspora
  .field.feed
    .helper
      :markdown
        #{t '.feed_helper'}
    = f.label :feed
    = f.url_field :feed, placeholder: 'Ex: http://april.org/index.rss'
  .field.contact
    .helper
      :markdown
        #{t '.contact_helper'}
    = f.label :contact
    = f.email_field :contact
  .field.submitter
    .helper
      :markdown
        #{t '.submitter_helper'}
    = f.label :submitter
    = f.email_field :submitter

  .field.tags
    .helper
      :markdown
        #{t '.tags_helper'}
    = f.label :tags
    = f.text_field :tag_list, value: f.object.tag_list.to_s

  .field.active
    = f.label :active
    = f.check_box :active

  .actions
    = f.button do
      %em.fa.fa-check
      = t '.save'

app/views/orgas/_search.html.haml
= search_form_for @search || Orga.search(params[:q]) do |f|
  = f.label :search, t('.label')
  %em.fa.fa-users
  = f.search_field :name_or_city_or_department_or_region_name_or_url_or_diaspora_or_tags_or_description_cont_any,
    id: :q_search, size: 16,
    placeholder: t('.title', entity: Orga.model_name.human)
  = f.button class: :search do
    %em.fa.fa-search
    %span.label= t '.label'

app/views/orgas/_types.haml
- params[:q] = {} if params[:q].nil?
- p = params[:q].clone

%ul.counters
  - Kind.all.each do |kind|
    - p[:kind_id_eq] = kind.id
    %li{ title: Kind.human_attribute_name("name_#{kind.name}") }
      = link_to orgas_url(q: p) do
        %em.fa{ class: "fa-#{kind.icon}" }
        = Orga.where(kind: kind).count

  %li
    - p[:kind_id_eq] = params[:q][:kind_id_eq]
    - p[:active_eq] = true
    = link_to orgas_url(q: p) do
      %em.fa.fa-heartbeat
      = Orga.where(active: true).count

app/views/orgas/cancel.html.haml
%h2
  %em.fa.fa-trash-o
  = t '.title'

- if @orga.moderated?
  %h3.warning= t '.already_moderated'

%fieldset
  = form_for @orga, method: :delete do |f|
    = hidden_field_tag :secret, params[:secret]
    %h2= t '.confirm'

    = f.submit t('.ok'), name: :yes
    = link_to t('.ko'), @orga, class: :button

%fieldset
  %legend= Orga.model_name.human
  = render file: '/orgas/show'

app/views/orgas/edit.html.haml
%h2
  %em.fa.fa-users
  = title t '.title'

%fieldset
  %legend
    %em.fa.fa-pencil
    = t '.edit'
  = render 'form'

app/views/orgas/index.html.haml
= render 'search'

%h2
  %em.fa.fa-users
  = title t '.title'

= render 'types'

%table.list.autopagerize_page_element
  %thead
    %th
    %th.name= sort_link @search, :name
    %th.city= sort_link @search, :city
    %th.department= sort_link @search, :department
    %th.region= sort_link @search,
      :region_name, Orga.human_attribute_name(:region)
    %th.tags= sort_link @search, :tags, Orga.human_attribute_name(:tags)
    %th.updated_at= sort_link @search,
      :updated_at, Orga.human_attribute_name(:updated_at)
    %th
    %th
    %th
    %th.view/
    %th.edit/

  %tbody
    - @orgas.each do |orga|
      %tr{ class: orga.active ? 'active' : 'inactive' }
        %td.kind
          - if orga.kind
            %em.fa{ class: "fa-#{orga.kind.icon}",
              title: Kind.human_attribute_name("name_#{orga.kind.name}") }
        %td.name
          = orga.name
          - if orga.url =~ /^http/
            = image_tag orga.url + '/favicon.ico', alt: '', class: :favicon
        %td.city= orga.city
        %td.department= orga.department
        %td.region= orga.region
        %td.tags= orga.tag_list
        %td.updated_at
          - if orga.updated_at.present?
            = l orga.updated_at.to_date
        %td.url
          - if orga.url.present?
            = link_to orga.url do
              %em.fa.fa-external-link{ title: Orga.human_attribute_name(:url) }
        %td.diaspora
          - if orga.diaspora.present?
            = link_to orga.diaspora do
              %em.fa.fa-bullhorn{ title: Orga.human_attribute_name(:diaspora) }
        %td.feed
          - if orga.feed.present?
            = link_to orga.feed do
              %em.fa.fa-rss{ title: Orga.human_attribute_name(:feed) }
        %td.view
          = link_to orga_path(orga, q: params[:q], page: params[:page]) do
            %em.fa.fa-eye
        %td.edit
          - if orga.secret.nil? || user_signed_in?
            = link_to edit_orga_path orga do
              %em.fa.fa-pencil

  %tfoot
    %tr
      %th(colspan='12')= paginate @orgas

app/views/orgas/new.html.haml
%h2
  %em.fa.fa-users
  = title t '.title'

%fieldset
  %legend
    %em.fa.fa-pencil
    = t '.edit'
  = render 'form'

app/views/orgas/show.html.haml
- set_orga_meta

%h2
  - if @orga.kind
    %em.fa{ class: "fa-#{@orga.kind.icon}",
      title: Kind.human_attribute_name("name_#{@orga.kind.name}") }
  = title @orga.name
  = image_tag @orga.url + '/favicon.ico', alt: '', class: :favicon

- if controller.controller_name == 'orgas' && controller.action_name == 'show'
  %aside
    %h1
      %em.fa.fa-link
      = t '.links'

    %ul.fa-ul
      %li
        = link_to orgas_path(q: params[:q], page: params[:page]),
          class: :back do
          %em.fa.fa-li.fa-arrow-left
          = Orga.model_name.human.pluralize
      %li
        = link_to tag_path @orga.name_as_tag do
          %em.fa.fa-li.fa-tag
          = Event.model_name.human.pluralize
      %li
        = link_to events_path tag: @orga.name_as_tag do
          %em.fa.fa-li.fa-calendar
          Agenda
      %li
        = link_to events_path format: :rss, tag: @orga.name_as_tag do
          %em.fa.fa-li.fa-rss
          RSS
      %li
        = link_to events_path format: :ics, tag: @orga.name_as_tag do
          %em.fa.fa-li.fa-th-list
          iCal
      %li
        = link_to maps_path tag: @orga.name_as_tag do
          %em.fa.fa-li.fa-map-marker
          OpenStreetMap
      %li
        = link_to maps_path format: :json, tag: @orga.name_as_tag do
          %em.fa.fa-li.fa-dot-circle-o
          GeoJSON

    - if @orga.secret.nil? || user_signed_in?
      %h1
        %em.fa.fa-wrench
        = t '.actions'
      %h2
        = link_to edit_orga_path @orga do
          %em.fa.fa-lg.fa-pencil
          = t '.edit'
      - if user_signed_in?
        %h2
          = link_to cancel_orga_path @orga do
            %em.fa.fa-lg.fa-thumbs-down
            = t '.cancel'

%p.full_address
  - if @orga.place_name.present?
    %span= @orga.place_name
  - if @orga.address.present?
    %span= @orga.address
  %span= link_to @orga.city,
    "http://fr.wikipedia.org/wiki/#{url_encode @orga.city}"
  %span= link_to @orga.region.try(:name),
    "http://fr.wikipedia.org/wiki/#{url_encode @orga.region.try :name}"

- if @orga.latitude && @orga.longitude
  .orga#map{ data: { url: "#{maps_path format: :json}",
    latitude: "#{@orga.latitude}", longitude: "#{@orga.longitude}" } }

%h3= t '.description'
.description
  = description sanitize @orga.description,
    tags: %w(p h1 h2 h3 h4 br table tr th td ul ol li a strong b em i img),
    attributes: %w(href src width height style)

%dl
  - if @orga.department.present?
    %dt
      %em.fa.fa-puzzle-piece
      = Orga.human_attribute_name :department
    %dd= @orga.department
  - if @orga.url.present?
    %dt
      %em.fa.fa-external-link
      = Orga.human_attribute_name :url
    %dd= link_to @orga.url, @orga.url
  - if @orga.diaspora.present?
    %dt
      %em.fa.fa-bullhorn
      = Orga.human_attribute_name :diaspora
    %dd= link_to @orga.diaspora, @orga.diaspora
  - if @orga.feed.present?
    %dt
      %em.fa.fa-rss
      = Orga.human_attribute_name :feed
    %dd= link_to @orga.feed, @orga.feed
  - if @orga.contact.present?
    %dt
      %em.fa.fa-envelope
      = Event.human_attribute_name :contact
    %dd= mail_to @orga.contact, nil,
      encode: (request.format == 'text/html' ? :javascript : nil),
      replace_at: ' CHEZ ', replace_dot: ' POINT '
  - if @orga.tags?
    %dt
      %em.fa.fa-tags
      = Event.human_attribute_name :tags
    %dd
      - @orga.tags.each do |tag|
        = link_to tag, tag_path(tag.name), rel: :tag
  %dt
    %em.fa.fa-heartbeat
    = Orga.human_attribute_name :active
  %dd= t @orga.active.to_s
  - if @orga.updated_at
    %dt
      %em.fa.fa-calendar
      = Orga.human_attribute_name :updated_at
    %dd= l @orga.updated_at.to_date, format: :long

  - if @events_future && @events_future.any?
    %dt
      %em.fa.fa-forward
      = t '.future'
    %dd
      = link_to tag_path @orga.name_as_tag do
        = t '.count', count: @events_future.count
  - if @events_future && @events_past.any?
    %dt
      %em.fa.fa-backward
      = t '.past'
    %dd
      = link_to tag_path @orga.name_as_tag do
        = t '.count', count: @events_past.count

app/views/orgas/show.text.haml
=====================================================
#{Orga.human_attribute_name(:kind).concat(':').ljust 12         } #{@orga.kind.name}
#{Orga.human_attribute_name(:name).concat(':').ljust 12         } #{@orga.name}
#{Orga.human_attribute_name(:place_name).concat(':').ljust 12   } #{@orga.place_name}
#{Orga.human_attribute_name(:address).concat(':').ljust 12      } #{@orga.address}
#{Orga.human_attribute_name(:city).concat(':').ljust 12         } #{@orga.city}
#{Orga.human_attribute_name(:department).concat(':').ljust 12   } #{@orga.department}
#{Orga.human_attribute_name(:region).concat(':').ljust 12       } #{@orga.region}
#{Orga.human_attribute_name(:url).concat(':').ljust 12          } #{@orga.url}
#{Orga.human_attribute_name(:diaspora).concat(':').ljust 12     } #{@orga.diaspora}
#{Orga.human_attribute_name(:feed).concat(':').ljust 12         } #{@orga.feed}
#{Orga.human_attribute_name(:contact).concat(':').ljust 12      } #{@orga.contact}
#{Orga.human_attribute_name(:submitter).concat(':').ljust 12    } #{@orga.submitter}
#{Orga.human_attribute_name(:tags).concat(':').ljust 12         } #{@orga.tag_list}
- if @orga.active.present?
  #{Orga.human_attribute_name(:active).concat(':').ljust 12     } #{t @orga.active.to_s}
- unless @orga.description.blank?
  #{Orga.human_attribute_name(:description).concat(':').ljust 12}
  = wrap(strip_tags(@orga.description).gsub(/&#13;/, '')).gsub /^/, '  '
=====================================================

app/views/orgas/validate.html.haml
%h2
  %em.fa.fa-exclamation-triangle
  = t '.title'

= form_for @orga, url: { action: :accept }, html: { method: :put } do |f|
  = link_to moderations_path do
    %em.fa.fa-arrow-left
    = t '.ko'

  = f.button do
    %em.fa.fa-thumbs-up
    = t '.ok'

%fieldset
  %legend
    %em.fa.fa-calendar
    = Orga.model_name.human
  = render file: '/orgas/show'