config/routes.rb
Rails.application.routes.draw do
  get 'stats', to: 'stats#index'
  get 'versions', to: 'versions#index'

  resources :users
  resources :events do
    get :cancel, on: :member
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: [:new, :create]
    patch :preview, on: :member
    get :validate, :refuse, on: :member
    put :accept, on: :member
  end
  resources :digests, only: [:index, :show]
  resources :regions, only: [:index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: [:index, :show]
  resources :maps, only: [:index, :show]
  resources :orgas do
    get :cancel, :validate, :refuse, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users,
             path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/models/event.rb
require 'schedule'

# This is the central ADL class, where are managed all events
class Event < ActiveRecord::Base
  extend SimpleCalendar
  include Schedule
  acts_as_taggable
  strip_attributes
  has_paper_trail ignore: [:last_updated, :lock_version, :secret, :submitter,
                           :decision_time, :latitude, :longitude]

  belongs_to :region
  # This is the scheduled first event
  belongs_to :event
  has_many :notes, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :title, presence: true
  validate :end_after_start
  RULES = %w(daily weekly monthly monthly_day).freeze
  validates :rule, allow_nil: true, inclusion: RULES
  validates :description, presence: true
  validates :city, presence: true
  validates :region, presence: true
  validates :url, presence: true, format: %r{\Ahttps?:\/\/.*\..*\z}
  validates :contact, email: true
  validates :submitter, email: true

  geocoded_by :full_address
  after_validation :geocode, if: (lambda do |obj|
    obj.address_changed? || obj.city_changed?
  end)

  # Mechanism to store some reason which can be used when sending notifications
  attr_accessor :reason

  before_create EventCallbacks
  after_create EventCallbacks

  before_update EventCallbacks
  after_update EventCallbacks

  after_destroy EventCallbacks

  scope :moderated, ->(*) { where moderated: true }
  scope :unmoderated, ->(*) { where moderated: false }
  scope :last_year, -> { where '? <= end_time', 1.year.ago }
  scope :past, -> { where 'start_time <= ?', Time.zone.now }
  scope :future, -> { where '? <= end_time', Time.zone.now }
  scope :daylimit, ->(d) { where 'end_time <= ?', d.to_i.days.from_now }
  scope :year, (lambda do |year|
    where '? <= end_time and start_time <= ?',
          Date.new(year.to_i, 1, 1).beginning_of_week,
          Date.new(year.to_i, 12, 31).end_of_week.end_of_day
  end)
  scope :month, (lambda do |start_date|
    where '? <= end_time and start_time <= ?',
          start_date.to_date.beginning_of_month.beginning_of_week,
          start_date.to_date.end_of_month.end_of_week.end_of_day
  end)
  scope :period, (lambda do |year, week|
    start_date = DateTime.commercial(year.to_i, week.to_i)
    where '? <= end_time and start_time <= ?',
          start_date, start_date.end_of_week.end_of_day
  end)
  scope :region, ->(region) { where region: region unless region == 'all' }
  scope :locality, ->(locality) { where locality: locality }
  scope :tag, ->(tag) { tagged_with tag }
  scope :geo, -> { where 'latitude is not null and longitude is not null' }

  before_validation on: :create do
    self.submission_time = Time.zone.now
    self.decision_time = Time.zone.now

    # Populate submitter using contact info if absent
    self.submitter = contact if submitter.blank?
  end

  before_validation on: :update do
    self.latitude = nil if address_changed?
    self.longitude = nil if address_changed?
  end

  def as_json(_options = {})
    { type: 'Feature', properties: {
      id: id, name: title, start_time: start_time, end_time: end_time,
      place_name: place_name, address: address, city: city, locality: locality,
      tags: tag_list, popupContent: "<a href=\"/events/#{id}\">#{self}</a>"
    }, geometry: { type: 'Point', coordinates: [longitude, latitude] } }
  end

  def full_address
    # Region seems to disturb openstreetmap :(
    # [address, city, region.try(:name)].compact.join ', '
    [address, city].compact.join ', '
  end

  def hashtags
    tag_list.map { |tag| "##{tag.tr('-', '_').camelize :lower}" }
  end

  def to_s
    "#{start_time.to_date} #{city}: #{title} #{hashtags.join(' ')}"
  end

  def to_tweet
    url = Rails.application.routes.url_helpers.event_url(
      self,
      host: ActionMailer::Base.default_url_options[:host]
    )

    tweet = "#{self} #{url}"
    if tweet.size >= 140
      tweet = "#{tweet[0, tweet.rindex(/\s/, 140 - url.size)]} #{url}"
    end
    tweet
  end

  private

  def end_after_start
    errors.add :end_time, :before_start if
      !end_time.blank? && !start_time.blank? && end_time <= start_time
  end
end

app/controllers/events_controller.rb
# Event life cycle
# This is a central part to this project
class EventsController < ApplicationController
  has_scope :region, :locality, :tag, :daylimit, :year
  has_scope :near, type: :hash, using: [:location, :distance]

  before_action :set_events, only: [:index]
  before_action :set_event, except: [:index, :new, :preview_create, :create]
  before_action :set_create_event, only: [:preview_create, :create]
  before_action :check_secret, only: [:edit, :preview, :update, :destroy]
  before_action :set_mailer_host
  rescue_from ActiveRecord::StaleObjectError, with: :locked

  def index
    respond_to do |format|
      format.html
      format.json { @events = @events.future }
      format.rss { @events = filter_for_rss }
      format.ics { @events = @events.last_year }
      format.xml
    end
  end

  # GET /events/new
  def new
    @event = Event.new start_time: Time.zone.now.change(min: 0) + 1.day,
                       end_time: Time.zone.now.change(min: 0) + 1.day + 1.hour
  end

  # POST /events/preview
  def preview_create
    @event.valid?
    render action: :new
  end

  # POST /events
  # POST /events.json
  def create
    respond_to do |format|
      if @event.save
        format.html { redirect_to :root, notice: t('.ok') }
        # 201 means :created
        format.json { render action: 'show', status: 201, location: @event }
      else
        format.html { render action: 'new' }
        # 422 means :unprocessable_entity
        format.json { render json: @event.errors, status: 422 }
      end
    end
  end

  # PATCH/PUT /events/1/preview
  def preview
    @event.attributes = event_params
    @event.valid?
    render action: :edit
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update event_params
        format.html { redirect_to :root, notice: t('.ok') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        # 422 means :unprocessable_entity
        format.json { render json: @event.errors, status: 422 }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.reason = params[:event][:reason]
    @event.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  private

  def set_events
    @events = apply_scopes Event.moderated
  end

  # Use callbacks to share common setup or constraints between actions
  def set_event
    @event = Event.moderated
    @event = Event.where secret: params[:secret] if params[:secret].present?
    @event = @event.find params[:id]
  end

  def set_create_event
    @event = Event.new event_params
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through
  def event_params
    params.require(:event)
          .permit :lock_version, :title, :start_time, :end_time, :repeat, :rule,
                  :description, :place_name, :address, :city, :region_id,
                  :locality, :url, :contact, :submitter, :tag_list
  end

  def filter_for_rss
    if params[:future].present? && params[:future] == 'false'
      @events.order 'id desc'
    else
      @events.future.order('id desc').limit 20
    end
  end

  def locked
    redirect_to edit_event_url(@event, secret: @event.secret),
                alert: t('staleObjectError')
  end

  # Check that you can only edit an existing event if you know its secret
  def check_secret
    redirect_to :root, alert: t(:forbidden, scope: [:events, :edit]) \
      unless params[:secret] == @event.secret
  end
end

app/helpers/events_helper.rb
# Helper for the event views
module EventsHelper
  def set_events_meta
    set_meta_tags \
      description: t('layouts.application.subtitle'),
      keywords: @events.map(&:tags).join(', ').split.group_by { |i| i }
                       .reject { |_k, v| v.size < 2 }.map { |k, _v| k },
      DC: {
        title: t('layouts.application.title'),
        subject: t('layouts.application.subtitle'),
        publisher: 'april'
      }
  end

  def set_event_meta
    set_meta_tags \
      keywords: @event.tag_list,
      DC: { title: @event.title, date: @event.start_time.to_s },
      geo: {
        placename: @event.city,
        region: @event.region,
        position: "#{@event.latitude};#{@event.longitude}",
        ICBM: "#{@event.latitude}, #{@event.longitude}"
      }
  end

  def display_date(event = @event)
    if event.start_time.to_date == event.end_time.to_date
      display_sameday event
    else
      display_multi_days event
    end
  end

  def display_sameday(event)
    t 'date.formats.same_day',
      date: l(event.start_time.to_date, format: :long),
      start: l(event.start_time, format: :hours),
      end: l(event.end_time, format: :hours)
  end

  def display_multi_days(event)
    t 'date.formats.period',
      start: l(event.start_time, format: :at),
      end: l(event.end_time, format: :at)
  end

  def wrap(s, width = 78)
    s.gsub(/(.{1,#{width}})(\s+|\Z)/, "\\1\n")
  end

  # Select the events to display in a month, sorted
  def month_events(events, date)
    events.select { |e| (e.start_time.to_date..e.end_time.to_date).cover? date }
          .sort_by(&:city)
  end
end

app/views/events/_event.haml
%li.event{ title: display_date(event) }
  - if event.locality?
    %em.locality.fa.fa-globe
  - elsif event.tags.any? { |t| t.name.include? 'libre-en-fete' }
    = image_tag 'lef-small.png', alt: 'LEF', width: 16, height: 16
  = link_to event do
    %strong.city{ title: event.address }= event.city
    = event.title
    - if event.repeat > 0
      %em.fa.fa-repeat{ title: event.schedule }

app/views/events/_form.html.haml
= form_for @event,
  url: { action: @event.new_record? ? :create : :update } do |f|
  - if @event.persisted?
    = f.hidden_field :lock_version
    - unless @moderation
      = hidden_field_tag :secret, params[:secret]

  - if @event.errors.any?
    #flash_messages
      - @event.errors.full_messages.each do |msg|
        %p.flash.alert= msg

  .field.title
    = f.label :title
    = f.text_field :title, required: true, placeholder: t('.title_helper')
  .field.start_time
    = f.label :start_time
    = f.datetime_select :start_time, default: 1.day.from_now
  .field.end_time
    = f.label :end_time
    = f.datetime_select :end_time, default: 1.day.from_now

  - unless @event.moderated?
    .field.repeat
      = f.label :repeat
      = f.number_field :repeat, in: 0..40, maxlength: 2, size: 2

    .field.rule
      .helper
        :markdown
          #{t '.rule_helper'}
      = f.label :rule
      %span.radios
        - Event::RULES.each do |rule|
          = f.radio_button :rule, rule
          = f.label "rule_#{rule}",
            t(rule, scope: 'activerecord.attributes.event.rule_values')

  .field.description
    .helper
      :markdown
        #{t '.description_helper'}
    = f.label :description
    = f.text_area :description, rows: 25, class: :description

  .field.place_name
    = f.label :place_name
    = f.text_field :place_name
  .field.address
    .helper
      :markdown
        #{t '.address_helper'}
    = f.label :address
    = f.text_field :address, list: :addresses
    %datalist#addresses
      - Event.where('address is not null').group(:address).order('count(address) desc').pluck(:address).each do |address|
        %option= address
  .field.city
    = f.label :city
    = f.text_field :city, required: true, list: :cities
    %datalist#cities
      - Event.group(:city).order('count(city) desc').pluck(:city).each do |city|
        %option= city
  .field.region
    = f.label :region
    = f.collection_select :region_id, Region.all, :id, :name,
      include_blank: true
  .field.locality
    = f.label :locality
    %span.radios
      = f.radio_button :locality, 0
      = f.label 'locality_0' do
        %em.fa.fa-shield
        = t 'attributes.locality_0'
      = f.radio_button :locality, 1
      = f.label 'locality_1' do
        %em.fa.fa-globe
        = t 'attributes.locality_1'

  .field.url
    .helper
      :markdown
        #{t '.url_helper'}
    = f.label :url
    = f.url_field :url, required: true, placeholder: 'Ex: http://april.org'
  .field.contact
    .helper
      :markdown
        #{t '.contact_helper'}
    = f.label :contact
    = f.email_field :contact, required: true
  .field.submitter
    .helper
      :markdown
        #{t '.submitter_helper'}
    = f.label :submitter
    = f.email_field :submitter
  .field.tags
    .helper
      :markdown
        #{t '.tags_helper'}
    = f.label :tags
    = f.text_field :tag_list, value: f.object.tag_list.to_s

  .actions
    = f.button formaction: :preview do
      %em.fa.fa-eye
      = t '.visualise'

    = f.button do
      %em.fa.fa-check
      = t '.save'

app/views/events/cancel.html.haml
%h2
  %em.fa.fa-trash-o
  = t '.title'

- if @event.moderated?
  %h3.warning= t '.already_moderated'

%fieldset
  = form_for @event, method: :delete do |f|
    = hidden_field_tag :secret, params[:secret]
    %h2= t '.confirm'

    .field.reason
      = f.label :reason
      = f.text_area :reason, cols: 40, rows: 5

    = f.submit t('.ok'), name: :yes
    = link_to t('.ko'), @event, class: :button

%fieldset
  %legend= Event.model_name.human
  = render file: '/events/show'

app/views/events/edit.html.haml
%h2
  %em.fa.fa-pencil
  =t '.title'

- if @event.moderated?
  %h3.warning
    %em.fa.fa-warning
    =t '.warning'

%fieldset
  %legend
    %em.fa.fa-eye
    =t '.preview'
  = render file: '/events/show'

%fieldset
  %legend
    %em.fa.fa-pencil
    =t '.edit'
  = render '/events/form'

app/views/events/index.html.haml
= render '/orgas/search'

- if params[:year]
  %header.calendar-header.year
    = link_to year: params[:year].to_i - 1, tag: params[:tag],
      region: params[:region] do
      %em.fa.fa-backward
    = params[:year]
    = link_to year: params[:year].to_i + 1, tag: params[:tag],
      region: params[:region] do
      %em.fa.fa-forward
    :ruby
      set_meta_tags(
        prev: url_for(year: params[:year].to_i - 1),
        next: url_for(year: params[:year].to_i + 1)
      )

  - (1..12).each do |i|
    - params[:start_date] = "#{params[:year]}-#{i}-01"

    = month_calendar do |date|
      - capture_haml do
        .day_number= date.day
        %ul.events.fa-ul= render month_events(@events, date)

- else
  -# One month calendar
  - params[:start_date] ||= Time.zone.today.beginning_of_month
  :ruby
    set_meta_tags(
      prev: url_for(start_date: params[:start_date].to_date - 1.month),
      next: url_for(start_date: params[:start_date].to_date + 1.month)
    )
  - @events = @events.month params[:start_date]
  = month_calendar events: @events do |date, events|
    - capture_haml do
      .day_number= date.day
      %ul.events.fa-ul= render events

.links
  = raw t '.calendar_in',
    rss: link_to('RSS', events_path(:rss,
      tag: params[:tag], region: params[:region])),
    webcal: link_to('webcal', events_path(tag: params[:tag],
      protocol: 'webcal', format: :ics, region: params[:region])),
    ical: link_to('iCal', events_path(:rss,
      tag: params[:tag], format: :ics, region: params[:region]))

  \-

  = link_to page_path('filter') do
    %em.fa.fa-filter
    = t '.filter'

/
  %a#banner(href='http://april.org/campagne')
    = image_tag 'priorite-logiciel-libre-je-soutiens-april_2_m.png',
      width: '374', height: '48',
      alt: 'Priorité au Logiciel Libre! Je soutiens l\'April.'

%a#banner(href='http://www.libre-en-fete.net')
  = image_tag 'lef.png', width: '180', height: '60', alt: 'Libre en Fete'

- set_events_meta

app/views/events/index.ics.erb
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//AgendaDuLibre.org
X-WR-CALNAME:<%= t('title', scope: [:layouts, :application]).gsub(/'/, '’') %>
X-WR-CALDESC:<%= t 'subtitle', scope: [:layouts, :application] %>
<% @events.find_each do |event| %>
BEGIN:VEVENT
DTSTART:<%= event.start_time.strftime '%Y%m%dT%H%M%S' %>
DTEND:<%= event.end_time.strftime '%Y%m%dT%H%M%S' %>
UID:<%= event.id %>@agendadulibre.org
SUMMARY:<%= event.title.gsub(',', '\,').gsub(';', '\;') %>
URL:<%= event_url event %>
DESCRIPTION:<%= strip_tags(event.description).gsub(/'/, '’').gsub(',', '\,').gsub(';', '\;').gsub(/^/, ' ') %>
LOCATION:<%= event.full_address.gsub(/,/, '\,') %>
END:VEVENT
<% end %>
END:VCALENDAR

app/views/events/new.html.haml
%h2
  %em.fa.fa-pencil
  =title t '.title'

-  if @event.description
  %fieldset
    %legend
      %em.fa.fa-eye
      =t '.preview'
    = render file: '/events/show'

- else
  :markdown
    #{t '.subtitle'}

  #advises
    :markdown
      #{t '.advises'}

%fieldset
  %legend
    %em.fa.fa-plus
    =t '.edit'
  = render 'form'

app/views/events/show.html.haml
- set_event_meta

- if @event.tags.any? { |t| t.name.include? 'libre-en-fete' }
  Cet événement s'inscrit dans le cadre de
  %a(href='http://www.libre-en-fete.net')
    = image_tag 'lef.png', width: '180', height: '60', alt: 'Libre en Fete',
      style: 'vertical-align: middle'

%h2
  - if @event.locality?
    %em.locality.fa.fa-globe{ title: t('attributes.locality_1') }
  - else
    %em.locality.fa.fa-shield{ title: t('attributes.locality_0') }
  %em.city{ title: @event.full_address }= @event.city
  = title @event.title

- if controller.controller_name == 'events' && controller.action_name == 'show'
  %aside#orga-list
    - if @event.region.present? && @event.region.orgas.present?
      %h1
        %em.fa.fa-users
        = t '.orga-list'
      %ul.fa-ul
        - @event.region.orgas.select(&:active).each do |orga|
          %li
            = link_to orga do
              - if orga.kind
                %em.fa.fa-li{ class: "fa-#{orga.kind.icon}",
                  title: Kind.human_attribute_name("name_#{orga.kind.name}") }
              = orga.name
              = image_tag orga.url + '/favicon.ico', alt: '', class: :favicon

    %h1
      %em.fa.fa-wrench
      = t '.actions'
    %h2
      = link_to event_path @event, protocol: :webcal, format: :ics do
        %em.fa.fa-lg.fa-calendar
        = t '.add_to_calendar'
    %h2
      = link_to preview_events_path(event: { title: @event.title,
        start_time: @event.start_time + 1.month,
        end_time: @event.end_time + 1.month,
        description: @event.description,
        place_name: @event.place_name,
        address: @event.address,
        city: @event.city,
        region_id: @event.region.id,
        locality: @event.locality,
        url: @event.url,
        tag_list: @event.tag_list.to_s }),
        method: :post do
        %em.fa.fa-copy
        = t '.copy'
    - if user_signed_in?
      %h2
        = link_to edit_moderation_path @event do
          %em.fa.fa-lg.fa-pencil
          = t '.edit'
      %h2
        = link_to cancel_event_path @event, secret: @event.secret do
          %em.fa.fa-lg.fa-thumbs-down
          = t '.cancel'

%h3= t '.dateAndPlace'

%p= display_date

%p.full_address
  - if @event.place_name.present?
    %span= @event.place_name
  - if @event.address.present?
    %span= @event.address
  %span= link_to @event.city,
    "http://fr.wikipedia.org/wiki/#{url_encode @event.city}"
  %span= link_to @event.region.try(:name),
    "http://fr.wikipedia.org/wiki/#{url_encode @event.region.try :name}"

- if @event.latitude && @event.longitude
  .event#map{ data: { url: maps_path(format: :json),
    latitude: @event.latitude, longitude: @event.longitude } }

- elsif controller.action_name != 'show'
  %em.fa.fa-compress
  %em
    = raw t '.noMap'
    %a{ href: 'http://osm.org/search?query=' + @event.full_address }
      %img(src='http://www.openstreetmap.org/assets/osm_logo.png'
        alt='OSM logo' width='22px')

%h3= t '.description'
.description
  = description sanitize @event.description,
    tags: %w(p h1 h2 h3 h4 br table tr th td ul ol li a strong b em i img),
    attributes: %w(href src width height style)

%h3
  %em.fa.fa-info-circle
  = t '.infos'
%p
  %em.fa.fa-external-link
  %span.label= Event.human_attribute_name :url
  = link_to @event.url, @event.url
%p
  %em.fa.fa-envelope
  %span.label= Event.human_attribute_name :contact
  = mail_to @event.contact, nil,
    encode: (request.format == 'text/html' ? :javascript : nil),
    replace_at: ' CHEZ ', replace_dot: ' POINT '

- if @event.tags && @event.tags.present?
  %p.tags
    %em.fa.fa-tags
    %span.label= Event.human_attribute_name :tags
    - @event.tags.each do |tag|
      = link_to tag, tag_path(tag.name), rel: :tag

- if @event.repeat > 0 && @event.rule
  %h3
    %em.fa.fa-repeat
    = @event.schedule

  - if @event.moderated?
    %ul
      %li= link_to_unless_current @event.event || @event, @event.event || @event
      - (@event.event || @event).events.each do |e|
        %li= link_to_unless_current e, e

app/views/events/show.ics.erb
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//AgendaDuLibre.org
X-WR-CALNAME:Agenda du Libre
X-WR-TIMEZONE:Europe/Paris
CALSCALE:GREGORIAN
X-WR-CALDESC:<%= t 'title', scope: [:layouts, :application] %>
<% event = @event %>
BEGIN:VEVENT
DTSTART;TZID=Europe/Paris:<%= event.start_time.strftime '%Y%m%dT%H%M%S' %>
DTEND;TZID=Europe/Paris:<%= event.end_time.strftime '%Y%m%dT%H%M%S' %>
UID:<%= event.id %>@agendadulibre.org
SUMMARY:<%= event.title %>
URL:<%= event_url event %>
DESCRIPTION:<%= strip_tags(event.description).gsub(/'/, '’').gsub(/,/, '\,').gsub(/;/, '\;').gsub /^/, ' ' %>
LOCATION:<%= event.full_address %>
END:VEVENT
END:VCALENDAR

app/views/events/show.text.haml
=====================================================
#{Event.human_attribute_name(:title).concat(':').ljust 12      } #{@event.title}
#{Event.human_attribute_name(:start_time).concat(':').ljust 12 } #{l @event.start_time, format: :at}
#{Event.human_attribute_name(:end_time).concat(':').ljust 12   } #{l @event.end_time, format: :at}
-if @event.repeat > 0
  #{Event.human_attribute_name(:repeat).concat(':').ljust 12   } #{@event.repeat}
  #{Event.human_attribute_name(:rule).concat(':').ljust 12     } #{t @event.rule, scope: 'activerecord.attributes.event.rule_values'}
#{Event.human_attribute_name(:place_name).concat(':').ljust 12 } #{@event.place_name}
#{Event.human_attribute_name(:address).concat(':').ljust 12    } #{@event.address}
#{Event.human_attribute_name(:city).concat(':').ljust 12       } #{@event.city}
#{Event.human_attribute_name(:region).concat(':').ljust 12     } #{@event.region}
#{Event.human_attribute_name(:locality).concat(':').ljust 12   } #{t "attributes.locality_#{@event.locality}"}
#{Event.human_attribute_name(:url).concat(':').ljust 12        } #{@event.url}
#{Event.human_attribute_name(:contact).concat(':').ljust 12    } #{@event.contact}
#{Event.human_attribute_name(:submitter).concat(':').ljust 12  } #{@event.submitter}
#{Event.human_attribute_name(:tags).concat(':').ljust 12       } #{@event.tag_list}
#{Event.human_attribute_name(:description).concat(':').ljust 12}
= wrap(strip_tags(@event.description).gsub(/&#13;/, '')).gsub /^/, '  '
=====================================================