config/routes.rb
Rails.application.routes.draw do
  get 'stats', to: 'stats#index'
  get 'versions', to: 'versions#index'

  resources :users
  resources :events do
    get :cancel, on: :member
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: [:new, :create]
    patch :preview, on: :member
    get :validate, :refuse, on: :member
    put :accept, on: :member
  end
  resources :digests, only: [:index, :show]
  resources :regions, only: [:index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: [:index, :show]
  resources :maps, only: [:index, :show]
  resources :orgas do
    get :cancel, :validate, :refuse, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users,
             path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/controllers/digests_controller.rb
# A digest of all events over a period of time
class DigestsController < ApplicationController
  has_scope :moderated, default: nil, allow_blank: true
  has_scope :region, :locality, :tag
  has_scope :period, allow_blank: true, type: :hash, using: [:year, :week],
                     default: (
                       lambda do
                         { year: (Time.zone.today + 7.days).year,
                           week: (Time.zone.today + 7.days).cweek }
                       end)

  before_action :set_week, if: -> { params[:period] }
  before_action :set_events, only: [:show]

  def show
    render :markdown
  end

  private

  def set_week
    @week = DateTime.commercial params[:period][:year].to_i,
                                params[:period][:week].to_i
  end

  def set_events
    @week ||= Time.zone.today + 7.days
    @events = apply_scopes Event
  end
end

app/views/digests/index.html.haml
hello world!!

app/views/digests/markdown.html.haml
- title = t '.title', week: @week.cweek, year: @week.year

- description = capture_haml do
  = t '.week', count: @events.count
  \

  - @events.group_by { |evt| evt.start_time.to_date }.sort.each do |day, evts|
    * #{l day, format: :long}
    - evts.each do |event|
      \  * [**#{event.city}**] [#{event.title}](#{event_url event})

- second_part = capture_haml do
  = title
  \=====

  - @events.sort_by(&:start_time).each do |event|
    [#{event.city}] [#{event.title}](#{event_url event}) - #{display_date event}
    \-----

    - lines = strip_tags(event.description).split(/\r\n/).reject(&:blank?)
    - lines[0..2].each do |p|
      = p
    \
    * #{[event.place_name, event.full_address].compact.join ', '}
    * #{Event.human_attribute_name :url}: #{link_to event.url, event.url}
    * #{Event.human_attribute_name :tags}:
    #{event.tags.collect { |tag| "[#{tag}](#{tag_url tag.name})" }.join ', '}
    \

%h1= title

%description
  :markdown
    #{description}

%hr

:markdown
  * [April](http://april.org)
  * [Agenda du Libre](http://www.agendadulibre.org)
  * [Carte des événements]
    (#{maps_url future: false, period: { year: @week.year, week: @week.cweek }})
  * [Proposer un événement](http://www.agendadulibre.org/events/new)
  * [Annuaire des organisations](http://www.agendadulibre.org/orgas)
  * [Agenda pour la semaine précédante]
    (#{digest_url :markdown, future: false, period: {
    year: @week.year, week: (@week - 1.week).cweek }})

%hr

.second_part
  :markdown
    #{second_part}

%hr

%form(action='https://linuxfr.org/news' method='post' accept-charset='UTF-8')
  %input(type='hidden' name='utf8' value='✓')
  %input(type='hidden' name='news[cc_licensed]' value='1')
  %input(type='hidden' name='news[section_id]' value='9')
  %input(type='hidden' name='tags' value='agenda_du_libre')
  %input(type='hidden' name='commit' value='Prévisualiser')

  .field.title
    %label(for='title') Titre
    %input#title{ type: 'text', name: 'news[title]', value: title }

  .field.authenticity_token
    %label(for='token') Jeton
    %input#token(type='text' name='authenticity_token' autocomplete='off')

  .field.description
    %label(for='description') Contenu
    %textarea#description(name='news[wiki_body]')= description

  .field.links
    %input(type='hidden' name='news[links_attributes][0][title]'
      value='April')
    %input(type='hidden' name='news[links_attributes][0][url]'
      value='http://april.org')
    %input(type='hidden' name='news[links_attributes][0][lang]'
      value='fr')

    %input(type='hidden' name='news[links_attributes][1][title]'
      value='Agenda du Libre')
    %input(type='hidden' name='news[links_attributes][1][url]'
      value='http://www.agendadulibre.org')
    %input(type='hidden' name='news[links_attributes][1][lang]'
      value='fr')

    %input(type='hidden' name='news[links_attributes][2][title]'
      value='Carte des événements')
    %input{ type: 'hidden', name: 'news[links_attributes][2][url]',
      value: maps_url(future: false,
      period: { year: @week.year, week: @week.cweek }) }
    %input(type='hidden' name='news[links_attributes][2][lang]'
      value='fr')

    %input(type='hidden' name='news[links_attributes][3][title]'
      value='Proposer un événement')
    %input(type='hidden' name='news[links_attributes][3][url]'
      value='http://www.agendadulibre.org/events/new')
    %input(type='hidden' name='news[links_attributes][3][lang]'
      value='fr' size='2')

    %input(type='hidden' name='news[links_attributes][4][title]'
      value='Annuaire des organisations')
    %input(type='hidden' name='news[links_attributes][4][url]'
      value="http://www.agendadulibre.org/orgas")
    %input(type='hidden' name='news[links_attributes][4][lang]'
      value='fr' size='2')

    %input(type='hidden' name='news[links_attributes][5][title]'
      value='Agenda de la semaine précédente')
    - pre = 'https://linuxfr.org/news/agenda-du-libre-pour-la-semaine-'
    - pre += "#{(@week - 1.week).cweek}-de-l-annee-#{(@week - 1.week).year}"
    %input{ type: 'hidden', name: 'news[links_attributes][5][url]', value: pre }
    %input(type='hidden' name='news[links_attributes][5][lang]'
      value='fr' size='2')

  .field.description
    %label(for='second_part') Seconde partie
    %textarea#second_part(name='news[wiki_second_part]')= second_part

  .actions
    %button
      %em.fa.fa-check
      Prévisualiser